# Site Info
title:              "Meta-note"
description:        "Personal Blog and Knowlege Warehouse"

# Google APIs
google_verify:      epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o # Your Google Verification - set to 'false' to disable
google_analytics:   UA-XXXXXXX-X # Your Google Analytics code - set to 'false' to disable

# Author Info
author_name:        "최원일 Choi Won-il"
author_email:       be.data.analyst.11@gmail.com
author_gravatar:    cfb2bd9d258d7ae2205873c2d8a93e67 # Gravatar md5 hash (of email) here for logo - set to 'false' to disable
twitter_username:   false # set to 'false' to disable
github_username:    11wi # set to 'false' to disable

# Site Settings
url:                https://11wi.io # main url
baseurl:            /page # for gh-pages
permalink:          /notes/:title # Post permalink
timezone:           Asia/Seoul # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
