# Site Info
title:              "Meta-notes"
description:        "Personal Blog and Technial Knowledge Warehouse"

# Google APIs
google_verify:      0RavclAqC5DcNunhPaS5gniBRyjhoDMqa8klD3seW_I # Your Google Verification - set to 'false' to disable
# https://support.google.com/webmasters/answer/35179?hl=en&visit_id=1-636605658266318966-3745163826&rd=1
# GA 사용을 위해 페이지 주인 인증을 해야하는데, html 태그 삽입 방식으로 인증.
google_analytics:   UA-118262874-1 # Your Google Analytics code - set to 'false' to disable

# Author Info
author_name:        "Heiswayi Nrird"
author_email:       hnrird@gmail.com
author_gravatar:    cfb2bd9d258d7ae2205873c2d8a93e67 # Gravatar md5 hash (of email) here for logo - set to 'false' to disable
twitter_username:   HeiswayiNrird # set to 'false' to disable
github_username:    heiswayi # set to 'false' to disable

# Site Settings
url:                https://11wi.github.io # main url
baseurl:            /the-plain # for gh-pages
permalink:          /notes/:title # Post permalink
timezone:           Asia/Seoul # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme

remote_theme: heiswayi/the-plain


defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
